name: Static Analysis
on:
  pull_request:
  push:
    branches: [main, zendriver]
  workflow_dispatch:

jobs:
  python-coding-style:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - run: uv run ruff check .

      - run: uv run ruff format --check .

  python-type-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - run: uv run pyright .
